on: [push,pull_request]
jobs:
  maanan:
    steps:
      - uses: actions/checkout@v2
      - run: g++ -Wall -o kostka kostka.cpp
      - run: ./kostka 
    runs-on: ${{matrix.platform}}
    strategy:
      matrix: 
        platform: [ubuntu-latest, macos-latest, windows-latest]
