on: [push,pull_request]
jobs:
  maanan:
    steps:
      - uses: actions/checkout@v2
    runs-on: ${{matrix.platform}}
    strategy:
      matrix: 
        platform: [ubuntu-latest, macos-latest, windows-latest]
